#!/usr/bin/env python3
"""Static rule scan for projects generated by ios-app-builder.

Enforces the automatable part of references/rules/*.md that SwiftLint, SwiftFormat and the compiler do not cover (or
cover too loosely). Each finding carries the rule ID from the rule files.

Usage: check_rules.py <project-root> [--json] [--module Packages/FeatureNotesList | --module App] [--final]
Exit 0 = no violations (warnings allowed), 1 = violations found.

Escape hatch: a line containing `rules-ignore: <RULE-ID> <reason>` (in a comment) skips that rule on that line and
the next one. The reason is mandatory and is reviewed in self-review.
"""
import argparse
import glob
import json
import os
import re
import sys
from collections import defaultdict

SKIP_DIRS = {".git", ".build", "build", "DerivedData", ".swiftpm", "SourcePackages", "node_modules", "vendor", "Pods"}
IGNORE = re.compile(r"rules-ignore:\s*([A-Z0-9_-]+)\s+\S+")
MAX_FILE_LINES, HARD_FILE_LINES = 300, 500
MIN_TEST_RATIO, MIN_FEATURE_TEST_RATIO = 0.4, 0.5
SYSTEM_COLORS = "red|blue|green|orange|yellow|pink|purple|gray|grey|white|black|brown|cyan|mint|teal|indigo"

DEPRECATED = [
    (r"\bNavigationView\b", "NavigationView (use NavigationStack)", "DEPR-01"),
    (r"\.foregroundColor\(", ".foregroundColor (use foregroundStyle)", "DEPR-01"),
    (r"\.cornerRadius\(", ".cornerRadius (use clipShape/.rect(cornerRadius:))", "DEPR-01"),
    (r"\.onChange\(of:[^)]*\)\s*\{\s*(?:newValue|value)\s+in", "onChange(of:) single-parameter closure", "DEPR-01"),
    (r"\.navigationBarTitle\(|\.navigationBarItems\(|\.accentColor\(", "legacy navigation/accent modifier", "DEPR-01"),
    (r"\bUIWebView\b|\bUIAlertView\b|\bUIActionSheet\b|\bActionSheet\(", "removed UIKit/SwiftUI alert APIs", "DEPR-02"),
    (r"NSKeyedUnarchiver\.unarchiveObject|NSKeyedArchiver\.archivedData\(withRootObject:\s*[^,)]*\)\s*$", "insecure NSKeyedArchiver", "DEPR-02"),
    (r"\bObservableObject\b|@Published\b|@StateObject\b|@ObservedObject\b|@EnvironmentObject\b", "ObservableObject stack (use @Observable)", "DEPR-03"),
    (r"^\s*import Combine\b", "Combine (use async/await and AsyncSequence)", "DEPR-04"),
    (r"\bUserDefaults\.standard\.synchronize\(", "UserDefaults.synchronize", "DEPR-02"),
]
STALE_LIBS = [
    (r"\bRxSwift\b|\bRxCocoa\b", "RxSwift"), (r"\bPromiseKit\b", "PromiseKit"), (r"\bSwiftyJSON\b", "SwiftyJSON"),
    (r"\bObjectMapper\b", "ObjectMapper"), (r"\bAlamofire\b.*from:\s*\"[1-4]\.", "Alamofire < 5"),
]
SECRET = re.compile(r"""(?i)\b(api[_-]?key|secret|client[_-]?secret|access[_-]?token|password|passwd)\b\s*[:=]\s*["'][^"'$\s\\]{8,}["']""")
SECRET_TOKENS = re.compile(r"AIza[0-9A-Za-z_\-]{35}|sk_live_[0-9A-Za-z]{10,}|ghp_[0-9A-Za-z]{30,}|xox[baprs]-[0-9A-Za-z-]{10,}|-----BEGIN [A-Z ]*PRIVATE KEY-----")
# API usage -> the Info.plist key iOS requires before the app may call it (PRIV-02)
USAGE_KEYS = [
    (r"\bAVCaptureDevice\b|\bAVCaptureSession\b|\bDataScannerViewController\b", "NSCameraUsageDescription"),
    (r"\bAVAudioRecorder\b|\bAVAudioApplication\.requestRecordPermission|AVAudioSession\.sharedInstance\(\)\.requestRecordPermission", "NSMicrophoneUsageDescription"),
    (r"\bCLLocationManager\b", "NSLocationWhenInUseUsageDescription"),
    (r"\bLAContext\b", "NSFaceIDUsageDescription"),
    (r"\bCNContactStore\b", "NSContactsUsageDescription"),
    (r"\bATTrackingManager\b", "NSUserTrackingUsageDescription"),
    (r"\bCMMotionManager\b|\bCMPedometer\b", "NSMotionUsageDescription"),
    (r"\bEKEventStore\b", "NSCalendarsFullAccessUsageDescription"),
    (r"\bPHPhotoLibrary\.requestAuthorization|\bPHPhotoLibrary\.shared", "NSPhotoLibraryUsageDescription"),
    (r"\bCBCentralManager\b|\bCBPeripheralManager\b", "NSBluetoothAlwaysUsageDescription"),
    (r"\bSFSpeechRecognizer\b", "NSSpeechRecognitionUsageDescription"),
]
# required-reason API usage -> privacy manifest category (PRIV-01)
REASON_APIS = [
    (r"\bUserDefaults\b|@AppStorage\b", "NSPrivacyAccessedAPICategoryUserDefaults"),
    (r"systemUptime|mach_absolute_time|\bProcessInfo\.processInfo\.systemUptime", "NSPrivacyAccessedAPICategorySystemBootTime"),
    (r"\.creationDate\b|\.modificationDate\b|contentModificationDateKey|creationDateKey|\bstat\(|attributesOfItem", "NSPrivacyAccessedAPICategoryFileTimestamp"),
    (r"volumeAvailableCapacity|systemFreeSize|volumeTotalCapacity|systemSize", "NSPrivacyAccessedAPICategoryDiskSpace"),
    (r"activeInputModes", "NSPrivacyAccessedAPICategoryActiveKeyboards"),
]


class Scanner:
    def __init__(self, root, module=None, final=False):
        self.root = os.path.realpath(root)
        self.module = module.strip("/") if module else None
        self.final = final
        self.findings = []
        self.languages = self.read_languages()

    # ------------------------------------------------------------ helpers
    def add(self, rule, severity, path, line, msg):
        self.findings.append({"rule": rule, "severity": severity, "file": self.rel(path), "line": line, "message": msg})

    def rel(self, path):
        return os.path.relpath(os.path.realpath(path), self.root).replace(os.sep, "/")

    def files(self, exts, base=None):
        base = base or (os.path.join(self.root, self.module) if self.module else self.root)
        for dp, dns, fns in os.walk(base):
            dns[:] = [d for d in dns if d not in SKIP_DIRS and not d.endswith(".xcodeproj")]
            for fn in fns:
                if os.path.splitext(fn)[1] in exts:
                    yield os.path.join(dp, fn)

    def all_files(self, exts):
        yield from self.files(exts, self.root)

    @staticmethod
    def read(path):
        with open(path, encoding="utf-8", errors="replace") as fh:
            return fh.read()

    @staticmethod
    def strip_comments(src):
        """Blank out comments (keeping line numbers); string contents stay because several rules inspect them."""
        out, i, n, in_str, in_multi = [], 0, len(src), False, False
        while i < n:
            c = src[i]
            if not in_str and not in_multi and src.startswith("//", i):
                j = src.find("\n", i)
                j = n if j == -1 else j
                out.append(" " * (j - i)); i = j; continue
            if not in_str and not in_multi and src.startswith("/*", i):
                j = src.find("*/", i + 2)
                j = n if j == -1 else j + 2
                out.append("".join(ch if ch == "\n" else " " for ch in src[i:j])); i = j; continue
            if src.startswith('"""', i):
                in_multi = not in_multi
                out.append('"""'); i += 3; continue
            if not in_multi and c == '"' and (i == 0 or src[i - 1] != "\\"):
                in_str = not in_str
            if in_str and c == "\n":
                in_str = False
            out.append(c); i += 1
        return "".join(out)

    @staticmethod
    def ignored(lines, idx, rule):
        for k in (idx, idx - 1):
            if 0 <= k < len(lines):
                m = IGNORE.search(lines[k])
                if m and m.group(1) == rule:
                    return True
        return False

    @staticmethod
    def preview_ranges(lines):
        """0-based inclusive line ranges of `#Preview { ... }` blocks."""
        ranges, i = [], 0
        while i < len(lines):
            if re.search(r"^\s*#Preview\b", lines[i]):
                depth, started, j = 0, False, i
                while j < len(lines):
                    depth += lines[j].count("{") - lines[j].count("}")
                    started = started or "{" in lines[j]
                    if started and depth <= 0:
                        break
                    j += 1
                ranges.append((i, j)); i = j + 1; continue
            i += 1
        return ranges

    @staticmethod
    def statement(code, i, span=5):
        """The line plus the following lines of the same call, so multi-line initializers can be inspected."""
        return " ".join(code[i:i + span])

    def read_languages(self):
        text = ""
        path = os.path.join(self.root, "project.yml")
        if os.path.exists(path):
            text = self.read(path)
        m = re.search(r"CFBundleLocalizations:\s*\[([^\]]*)\]", text)
        if m:
            return [x.strip() for x in m.group(1).split(",") if x.strip()]
        return []

    def catalogs(self):
        base = os.path.join(self.root, "Packages", "CoreLocalization", "Sources")
        return sorted(glob.glob(os.path.join(base, "**", "*.xcstrings"), recursive=True))

    def catalog_keys(self):
        """table -> {key base -> full key}"""
        tables = {}
        for path in self.catalogs():
            table = os.path.splitext(os.path.basename(path))[0]
            try:
                with open(path, encoding="utf-8") as fh:
                    keys = json.load(fh).get("strings", {})
            except (OSError, ValueError):
                continue
            tables[table] = {k.split(" ")[0]: k for k in keys}
        return tables

    # ------------------------------------------------------------ swift sources
    def scan_swift(self):
        tables = self.catalog_keys()
        for path in self.files({".swift"}):
            rel = self.rel(path)
            if os.path.basename(path) == "Package.swift":
                continue
            is_test = "/Tests/" in rel or rel.startswith(("AppTests/", "AppUITests/"))
            raw = self.read(path)
            raw_lines = raw.split("\n")
            code = self.strip_comments(raw).split("\n")
            if is_test:
                self.scan_test_file(path, rel, raw_lines, code)
                continue
            self.scan_production_file(path, rel, raw, raw_lines, code, tables)

    def scan_test_file(self, path, rel, raw_lines, code):
        for i, line in enumerate(code):
            if re.search(r"#expect\(\s*true\s*\)|#expect\(\s*1\s*==\s*1\s*\)|XCTAssertTrue\(\s*true\s*\)", line):
                self.add("TEST-05", "violation", path, i + 1, "trivial assertion")
            if re.search(r"\.disabled\(|@Test\([^)]*\.disabled|XCTSkip\(", line) and not self.ignored(raw_lines, i, "TEST-05"):
                self.add("TEST-05", "violation", path, i + 1, "disabled or skipped test")
            if re.search(r"^\s*import XCTest\b", line) and "/UITests" not in rel and not rel.startswith("AppUITests/"):
                self.add("TEST-06", "violation", path, i + 1, "XCTest outside UI tests: write the test with Swift Testing")
            if "@unchecked Sendable" in line and "justified:" not in raw_lines[i]:
                self.add("CORE-10", "violation", path, i + 1, "@unchecked Sendable without '// justified: <reason>'")

    def scan_production_file(self, path, rel, raw, raw_lines, code, tables):
        parts = rel.split("/")
        module = parts[1] if parts[0] == "Packages" else "App"
        in_ds = module == "CoreDesignSystem"
        in_feature = module.startswith("Feature")
        in_app = module == "App"
        base = os.path.basename(path)
        previews = self.preview_ranges(raw_lines)
        in_preview = lambda i: any(a <= i <= b for a, b in previews) or "PreviewData" in base
        has_body = bool(re.search(r"var\s+body\s*:\s*some\s+View", raw))

        if not any(l.strip() and not l.strip().startswith("//") for l in raw_lines):
            self.add("DEAD-06", "warning", path, 1, "placeholder file with no code: delete it")
        n = len(raw_lines)
        if n > HARD_FILE_LINES:
            self.add("CORE-02", "violation", path, 1, "%d lines (> %d)" % (n, HARD_FILE_LINES))
        elif n > MAX_FILE_LINES:
            self.add("CORE-02", "violation", path, 1, "%d lines (> %d): split the file" % (n, MAX_FILE_LINES))

        for i, line in enumerate(code):
            ln, rl = i + 1, raw_lines[i]

            def hit(rule, sev, msg):
                if not self.ignored(raw_lines, i, rule):
                    self.add(rule, sev, path, ln, msg)

            if re.search(r"\b(TODO|FIXME|HACK)\b", rl):
                hit("CORE-09", "violation", "TODO/FIXME/HACK left in code")
            if re.search(r"swiftlint:disable(?!:next|:this|:previous)", rl) or re.search(r"swiftformat:disable\s*$", rl):
                hit("CORE-10", "violation", "blanket lint disable: use disable:next with a justification")
            if re.search(r"swiftlint:disable:(next|this|previous)", rl) and "justified:" not in rl:
                hit("CORE-10", "violation", "lint suppression without '// justified: <reason>'")
            if re.search(r"@unchecked Sendable|nonisolated\(unsafe\)|@preconcurrency|unsafeBitCast", line) and "justified:" not in rl:
                hit("CORE-10", "violation", "concurrency/safety escape hatch without '// justified: <reason>'")
            if re.search(r"\bTask\.detached\b", line):
                hit("CONC-02", "violation", "Task.detached: use structured concurrency or an actor")
            if re.search(r"\bDispatchQueue\b|\bDispatchGroup\b|\bDispatchSemaphore\b|\bOperationQueue\b|\bNSLock\b", line):
                hit("CONC-03", "violation", "GCD/locks: use async/await, actors or MainActor")
            if re.search(r"\b(?:print|debugPrint|NSLog|dump|os_log)\(", line) and not re.search(r"\.(print|dump)\(", line):
                hit("SEC-06", "violation", "print/NSLog/os_log: log through AppLogger (OBS-01)")
            if re.search(r"\bLogger\(subsystem", line) and module != "CoreCommon":
                hit("SEC-06", "violation", "create loggers with AppLogger.make(category:) only")
            if re.search(r"privacy:\s*\.public", line) and re.search(r"(?i)token|password|secret|email|phone|name|address", line):
                hit("SEC-06", "violation", "possibly sensitive value logged with privacy: .public")
            if re.search(r"\bData\(contentsOf:|\bString\(contentsOf:|Thread\.sleep|\.contentsOfDirectory\(atPath", line):
                hit("PERF-01", "violation", "blocking I/O or sleep: use async APIs off the main actor")
            if re.search(r"\bString\(format:", line) and "locale:" not in self.statement(code, i, 2):
                hit("I18N-10", "violation", "String(format:) without an explicit locale")
            if re.search(r"\bDateFormatter\(\)|\.dateFormat\s*=|\bNumberFormatter\(\)", line):
                hit("I18N-11", "violation", "DateFormatter/NumberFormatter: use Date.FormatStyle / .formatted(...) with a locale")
            if re.search(r"\.padding\(\s*\.(left|right)\b|HorizontalAlignment\.(left|right)|\.(left|right)\s*,\s*\d", line):
                hit("I18N-13", "violation", "left/right edges do not mirror in right-to-left languages: use leading/trailing")
            if re.search(r"MessageDigest|\bInsecure\.(MD5|SHA1)\b|\bCC_(MD5|SHA1)\b|kCCAlgorithm(DES|3DES|RC4)", line):
                hit("SEC-05", "violation", "insecure crypto (MD5/SHA-1/DES/RC4)")
            if re.search(r"URLCredential\(trust:", line) and "SecTrustEvaluateWithError" not in raw:
                hit("SEC-05", "violation", "server trust accepted without SecTrustEvaluateWithError")
            if re.search(r"UserDefaults|@AppStorage", line) and re.search(r"(?i)token|password|secret|credential|apikey", line):
                hit("SEC-08", "violation", "secret in UserDefaults: use the Keychain (HARD-02)")
            if re.search(r"UIPasteboard\.general\.(string|strings|setValue)\s*=", line) and re.search(r"(?i)token|password|secret", line):
                hit("SEC-08", "violation", "secret copied to the general pasteboard")
            if re.search(r"NSAllowsArbitraryLoads|NSExceptionAllowsInsecureHTTPLoads", line):
                hit("SEC-02", "violation", "App Transport Security disabled")
            if SECRET.search(rl) or SECRET_TOKENS.search(rl):
                hit("SEC-01", "violation", "possible hard-coded secret")
            if re.search(r"""["']https?://[^"'\s]+["']""", line) and not in_preview(i) and "apple.com" not in rl \
                    and "www.w3.org" not in rl:
                hit("ENV-01", "violation", "hard-coded URL: URLs come from the active xcconfig through Info.plist")
            if re.search(r"catch\s*(\([^)]*\))?\s*\{\s*\}", line):
                hit("ERR-02", "violation", "empty catch block")
            if re.search(r"\btry\?", line) and "Task.sleep" not in line and not in_preview(i):
                hit("ERR-03", "warning", "try? discards the error: handle it or map it to a typed failure")
            if re.search(r"\bAnyView\b", line):
                hit("UI-06", "violation", "AnyView defeats SwiftUI diffing: use @ViewBuilder or generics")
            if re.search(r"\bid:\s*\\\.self\b", line):
                hit("UI-05", "warning", "id: \\.self is not a stable identity for non-primitive values: make the element Identifiable")
            if re.search(r"ForEach\(\s*(0\s*\.\.<|[\w.]+\.indices)", line):
                hit("UI-05", "warning", "ForEach over indices breaks identity when the data changes")
            if re.search(r"\.onAppear\s*\{", line) and re.search(r"\bTask\s*\{", self.statement(code, i, 3)):
                hit("UI-04", "violation", ".onAppear { Task { … } }: use .task, it is cancelled with the view")
            if re.search(r"\.onTapGesture\b", line):
                hit("A11Y-04", "violation", "tap gesture on a non-control: use a Button so VoiceOver and Switch Control work")
            if re.search(r"\.font\(\.system\(size:|UIFont\.systemFont\(ofSize|Font\.system\(size:", line) and not in_ds:
                hit("A11Y-05", "violation", "fixed font size does not follow Dynamic Type: use theme typography")
            for pattern, name, rule in DEPRECATED:
                if re.search(pattern, line):
                    hit(rule, "violation", "deprecated/legacy API: %s" % name)
            for pattern, key in REASON_APIS:
                if re.search(pattern, line):
                    self.reason_apis.setdefault(key, (path, ln))
            for pattern, key in USAGE_KEYS:
                if re.search(pattern, line):
                    self.usage_apis.setdefault(key, (path, ln))

            if not in_preview(i):
                text_call = re.search(r"\bText\(\s*\"", line) and "verbatim" not in line
                other_call = re.search(r"\b(Label|Button|Section|Toggle|TextField|SecureField|Link|Picker|ContentUnavailableView|"
                                       r"NavigationLink|DisclosureGroup|Menu|GroupBox)\(\s*\"", rl)
                modifier = re.search(r"\.(navigationTitle|accessibilityLabel|accessibilityHint|accessibilityValue|alert|"
                                     r"confirmationDialog|searchable|help|badge)\(\s*\"", rl)
                if text_call and "bundle: .localization" not in self.statement(code, i, 3):
                    hit("I18N-08", "violation", "Text(\"…\") without tableName: and bundle: .localization: copy lives in the string catalogs")
                if other_call or modifier:
                    hit("I18N-08", "violation", "string literal as user-facing text: look it up with String(localized:table:bundle: .localization)")
                if re.search(r"UIAlertController\(title:\s*\"", line):
                    hit("I18N-08", "violation", "hard-coded alert text")
                if not in_ds:
                    if re.search(r"\b(?:Color|UIColor)\(\s*(?:red|white|hue|\.sRGB|\.displayP3|cgColor|rgb|hex)", line) or \
                            re.search(r"\bColor\.(%s)\b" % SYSTEM_COLORS, line) or \
                            re.search(r"\.(?:foregroundColor|foregroundStyle|background|tint|fill|stroke|accentColor)\(\s*\.(%s)\b" % SYSTEM_COLORS, line):
                        hit("RES-01", "violation", "hard-coded color outside CoreDesignSystem: use theme colors")
                    if re.search(r"\.padding\(\s*(?:\.\w+\s*,\s*)?[1-9]\d*(?:\.\d+)?\s*\)", line) or \
                            re.search(r"\.frame\([^)]*\b(?:width|height|minWidth|minHeight|maxWidth|maxHeight|idealWidth|idealHeight):\s*[1-9]", line) or \
                            re.search(r"\b(?:spacing|cornerRadius|lineWidth|radius):\s*[1-9]\d*(?:\.\d+)?", line) or \
                            re.search(r"\.offset\(", line):
                        hit("RES-02", "violation", "hard-coded dimension outside CoreDesignSystem: use theme spacing tokens")
                    if re.search(r"\bImage\(\s*\"", line) and in_feature:
                        hit("RES-03", "violation", "bundled image literal in a feature: expose it from CoreDesignSystem")
            if in_feature:
                if re.search(r"\bTextField\(|\bSecureField\(|\bToggle\(|\.alert\(|\.confirmationDialog\(|\bButton\(\s*(\"|String\()", line) \
                        and not in_preview(i):
                    hit("DS-02", "violation", "raw SwiftUI control in a feature: use the CoreDesignSystem wrapper (add it first if missing)")
                if re.search(r"^\s*import\s+(CoreNetwork|CoreDatabase|CoreStorage|SwiftData)\b", line):
                    hit("ARCH-04", "violation", "feature imports the data layer directly: go through a repository protocol")
                if re.search(r"@Query\b|\bmodelContext\b|\bModelContext\(|mainContext", line):
                    hit("ARCH-04", "violation", "SwiftData used in a feature: repositories own the database")
                if re.search(r"\bNavigationStack\(|\bNavigationPath\b|\.navigationDestination\(|\bNavigationLink\(", line) and not in_preview(i):
                    hit("ARCH-08", "violation", "navigation structure belongs to the app target: expose a Key and an Entry, report taps with callbacks")
            if module in ("CoreModel", "CoreDomain") and re.search(r"^\s*import\s+(SwiftUI|UIKit|SwiftData|CoreData|Combine|Observation)\b", line):
                hit("ARCH-05", "violation", "UI/storage framework imported into a pure module")
            if in_ds and (re.search(r"bundle:\s*\.localization|String\(localized:", line) or re.search(r"^\s*import\s+CoreLocalization\b", line)):
                hit("DS-03", "violation", "designsystem must not look up strings: take text as a parameter")
            if re.search(r"URLSession(\.shared|\()", line) and module != "CoreNetwork":
                hit("DATA-03", "violation", "URLSession outside CoreNetwork: go through APIClient and safeApiCall")
            if module == "CoreDatabase" and re.search(r"removeItem\(|\.sqlite|default\.store", line):
                hit("DATA-04", "violation", "never delete or recreate the store file: ship a migration instead")
            if re.search(r"\bModelContainer\(for:", line) and not base == "AppDatabase.swift":
                hit("DATA-04", "violation", "build the container only in AppDatabase (versioned schema + migration plan)")
            if in_app and re.search(r"\bpath\.(append|removeLast|removeAll)\b|\.path\s*=", line) and base != "Router.swift" and "$router.path" not in line:
                hit("ARCH-10", "violation", "mutate the back stack through Router.navigate(to:) / goBack() only")

        if base.endswith("ViewModel.swift"):
            for cls in re.finditer(r"^(?:\s*(?:@\w+\s+)*)(?:final\s+)?class\s+(\w+)", raw, re.MULTILINE):
                header = raw[max(0, cls.start() - 120):cls.end()]
                if "@MainActor" not in header or "@Observable" not in header:
                    self.add("ARCH-11", "violation", path, raw[:cls.start()].count("\n") + 1,
                             "%s must be @MainActor and @Observable" % cls.group(1))
            if not re.search(r"\bvar\s+uiState\b", raw):
                self.add("ARCH-03", "violation", path, 1, "ViewModel exposes no `uiState` (one UiState per ViewModel)")
            for i, line in enumerate(code):
                if re.search(r"\bTask\s*(\{|\()", line) and not self.ignored(raw_lines, i, "CONC-08"):
                    self.add("CONC-08", "violation", path, i + 1, "unstructured Task in a ViewModel: expose an async func and let .task drive it")
                if re.search(r"\bTask\.sleep\(", line):
                    self.add("CONC-01", "warning", path, i + 1, "inject time (a sleep closure or clock) so tests do not wait")
        if base.endswith("UiState.swift"):
            for i, line in enumerate(code):
                if re.search(r"^\s*(public\s+)?var\s+\w+\s*:", line):
                    self.add("CORE-07", "violation", path, i + 1, "UI state is immutable: use `let`")
        if base.endswith("Screen.swift") and re.search(r"ViewModel", "\n".join(code)):
            self.add("UI-01", "violation", path, 1, "a Screen must not reference a ViewModel: pass state and callbacks in (the Route owns the ViewModel)")
        if has_body and (in_ds or in_feature or module == "CoreUI") and "#Preview" not in raw \
                and not base.endswith(("Route.swift", "Navigation.swift")):
            self.add("UI-03" if not in_ds else "DS-06", "violation", path, 1, "view file without #Preview (light and dark)")

    # ------------------------------------------------------------ Package.swift
    def scan_packages(self):
        for manifest in glob.glob(os.path.join(self.root, "Packages", "*", "Package.swift")):
            module = os.path.basename(os.path.dirname(manifest))
            if self.module and not self.module.startswith("Packages/%s" % module) and self.module != "Packages":
                continue
            src = self.strip_comments(self.read(manifest))
            lines = src.split("\n")
            tools = re.search(r"swift-tools-version:\s*(\d+)\.(\d+)", self.read(manifest))
            if not tools or (int(tools.group(1)), int(tools.group(2))) < (6, 0):
                self.add("BUILD-03", "violation", manifest, 1, "swift-tools-version must be 6.0 or newer (Swift 6 language mode)")
            if re.search(r"swiftLanguageModes:\s*\[[^\]]*\.v5|\.swiftLanguageVersion\(\.v5\)|-swift-version\s+5", src):
                self.add("BUILD-03", "violation", manifest, 1, "Swift 5 language mode: stay on Swift 6 strict concurrency")
            if "unsafeFlags" in src:
                self.add("BUILD-07", "violation", manifest, 1, "unsafeFlags are forbidden")
            for m in re.finditer(r"\.(?:target|testTarget)\(\s*name:\s*\"(\w+)\"(.*?)\n\s{8}\)", src, re.DOTALL):
                if "swiftSettings: strict" not in m.group(2) and ".treatAllWarnings(as: .error)" not in m.group(2):
                    self.add("BUILD-04", "violation", manifest, src[:m.start()].count("\n") + 1,
                             "target %s does not apply the strict swiftSettings (warnings are errors)" % m.group(1))
            for i, line in enumerate(lines):
                for pattern, name in STALE_LIBS:
                    if re.search(pattern, line):
                        self.add("BUILD-06", "violation", manifest, i + 1, "stale library: %s" % name)
                if module.startswith("Feature") and re.search(r'\.package\(path:\s*"\.\./Feature', line):
                    self.add("ARCH-01", "violation", manifest, i + 1, "feature depends on another feature: go through the app target")
                if module == "CoreDesignSystem" and re.search(r'\.package\(path:\s*"\.\./(CoreLocalization|CoreModel|CoreRepository)', line):
                    self.add("DS-03", "violation", manifest, i + 1, "designsystem depends on %s" % re.search(r"\.\./(\w+)", line).group(1))
                if module in ("CoreModel", "CoreDomain") and re.search(r'\.package\(path:\s*"\.\./Core(Network|Database|Storage|UI|DesignSystem)', line):
                    self.add("ARCH-05", "violation", manifest, i + 1, "pure module depends on an infrastructure module")
                if re.search(r"\.package\(url:", line) and "exact:" not in line:
                    self.add("BUILD-05", "violation", manifest, i + 1, "remote packages are pinned with exact: (run scripts/resolve_versions.py)")
        for forbidden in ("Podfile", "Cartfile"):
            if os.path.exists(os.path.join(self.root, forbidden)):
                self.add("BUILD-06", "violation", os.path.join(self.root, forbidden), 1, "%s: use Swift Package Manager" % forbidden)

    # ------------------------------------------------------------ repository hygiene, strings, privacy
    def scan_files_and_secrets(self):
        for path in self.all_files({".p8", ".p12", ".cer", ".mobileprovision", ".keychain"}):
            self.add("HARD-07", "violation", path, 1, "signing material in the repository")
        for path in self.all_files({".json"}):
            if os.path.basename(path) in {".swiftlint.baseline.json", "swiftlint-baseline.json"}:
                self.add("BUILD-02", "violation", path, 1, "lint baseline present: fix the findings instead")
        for path in self.all_files({".yml", ".yaml", ".xcconfig", ".rb", ".sh", ".plist", ".swift"}):
            rel = self.rel(path)
            if "/Tests/" in rel or rel.startswith("AppTests") or rel.endswith("example.xcconfig"):
                continue
            text = self.read(path)
            if rel == "Packages/CoreNetwork/Tests" or "check_rules" in rel:
                continue
            for i, line in enumerate(text.split("\n")):
                if "rules-ignore" in line or line.lstrip().startswith(("//", "#")):
                    continue
                if SECRET_TOKENS.search(line):
                    self.add("SEC-01", "violation", path, i + 1, "possible hard-coded secret")
                if re.search(r"NSAllowsArbitraryLoads|NSExceptionAllowsInsecureHTTPLoads", line):
                    self.add("SEC-02", "violation", path, i + 1, "App Transport Security disabled")

    def scan_strings(self):
        for path in self.all_files({".xcstrings"}):
            rel = self.rel(path)
            if not rel.startswith("Packages/CoreLocalization/") and rel != "App/InfoPlist.xcstrings":
                self.add("I18N-01", "violation", path, 1, "string catalogs live in CoreLocalization (InfoPlist.xcstrings may live in App/)")
        if self.module and not self.module.endswith("CoreLocalization"):
            return
        values = defaultdict(list)
        for path in self.catalogs():
            table = os.path.splitext(os.path.basename(path))[0]
            try:
                with open(path, encoding="utf-8") as fh:
                    data = json.load(fh)
            except (OSError, ValueError) as err:
                self.add("I18N-04", "violation", path, 1, "unreadable catalog: %s" % err)
                continue
            if not re.match(r"^[a-z][a-z0-9]*$", table):
                self.add("I18N-02", "violation", path, 1, "catalog name '%s' must be the lowercase feature name (one catalog per feature)" % table)
            default = data.get("sourceLanguage", "en")
            wanted = self.languages or [default]
            for key, entry in data.get("strings", {}).items():
                base = key.split(" ")[0]
                if not base.startswith(table + "_"):
                    self.add("I18N-03", "violation", path, 1, "key '%s' must start with '%s_'" % (key, table))
                if entry.get("shouldTranslate") is False:
                    continue
                loc = entry.get("localizations", {})
                for lang in wanted:
                    unit = loc.get(lang, {})
                    ok = unit.get("stringUnit", {}).get("state") == "translated" and unit.get("stringUnit", {}).get("value", "").strip()
                    plural = unit.get("variations", {}).get("plural", {}).get("other", {}).get("stringUnit", {}).get("value", "")
                    if not ok and not plural:
                        self.add("I18N-04", "violation", path, 1, "'%s' has no translated %s text" % (key, lang))
                default_text = loc.get(default, {}).get("stringUnit", {}).get("value")
                if default_text and table != "common":
                    values[default_text.strip().lower()].append((table, key))
                for lang, unit in loc.items():
                    if self.languages and lang not in self.languages:
                        self.add("I18N-12", "violation", path, 1, "'%s' has a %s localization the app does not declare (CFBundleLocalizations)" % (key, lang))
        common_values = set()
        for path in self.catalogs():
            if os.path.basename(path) == "common.xcstrings":
                try:
                    with open(path, encoding="utf-8") as fh:
                        for entry in json.load(fh).get("strings", {}).values():
                            for unit in entry.get("localizations", {}).values():
                                text = unit.get("stringUnit", {}).get("value")
                                if text:
                                    common_values.add(text.strip().lower())
                except (OSError, ValueError):
                    pass
        for text, owners in values.items():
            tables = {t for t, _ in owners}
            if text in common_values or len(tables) > 1:
                self.add("I18N-05", "violation", self.root, 1, "duplicate text %r in %s: move it to common.xcstrings" %
                         (text, ", ".join("%s:%s" % o for o in owners)))
        self.scan_string_lookups()

    def scan_string_lookups(self):
        """Every lookup names an existing key, in the table its prefix says, through the localization bundle."""
        tables = self.catalog_keys()
        used = set()
        for path in self.files({".swift"}, os.path.join(self.root, "Packages")):
            rel = self.rel(path)
            if "/Tests/" in rel or "/CoreLocalization/" in rel:
                continue
            code = self.strip_comments(self.read(path)).split("\n")
            raw_lines = self.read(path).split("\n")
            for i, line in enumerate(code):
                m = re.search(r'(?:String\(localized:|\bText\()\s*"([a-z][a-z0-9]*_[A-Za-z0-9_]*)', line)
                if not m:
                    continue
                key = m.group(1)
                stmt = self.statement(code, i, 4)
                table_match = re.search(r'(?:table|tableName):\s*"(\w+)"', stmt)
                if "bundle: .localization" not in stmt or not table_match:
                    if not self.ignored(raw_lines, i, "I18N-06"):
                        self.add("I18N-06", "violation", path, i + 1, "look strings up with table: and bundle: .localization")
                    continue
                table = table_match.group(1)
                if not key.startswith(table + "_"):
                    self.add("I18N-06", "violation", path, i + 1, "key '%s' does not belong to table '%s'" % (key, table))
                elif key not in tables.get(table, {}):
                    self.add("I18N-06", "violation", path, i + 1, "key '%s' is missing in %s.xcstrings" % (key, table))
                used.add(key)

    def scan_privacy(self):
        if self.module:
            return
        manifest = os.path.join(self.root, "App", "PrivacyInfo.xcprivacy")
        if not os.path.exists(os.path.join(self.root, "project.yml")):
            return  # the app target (D0) does not exist yet
        if not os.path.exists(manifest):
            self.add("PRIV-01", "violation", self.root, 1, "App/PrivacyInfo.xcprivacy is missing")
            return
        text = self.read(manifest)
        for key, (path, line) in sorted(self.reason_apis.items()):
            if key not in text:
                self.add("PRIV-01", "violation", path, line, "uses a required-reason API: declare %s in PrivacyInfo.xcprivacy" % key)
        project = os.path.join(self.root, "project.yml")
        if os.path.exists(project):
            yml = self.read(project)
            if "ITSAppUsesNonExemptEncryption" not in yml:
                self.add("PRIV-07", "violation", project, 1, "set ITSAppUsesNonExemptEncryption in the Info.plist properties")
            for key, (path, line) in sorted(self.usage_apis.items()):
                if key not in yml:
                    self.add("PRIV-02", "violation", path, line, "uses a protected API: add %s to the Info.plist properties (localized)" % key)

    def test_ratio(self):
        mods = defaultdict(lambda: [0, 0])
        for path in self.all_files({".swift"}):
            rel = self.rel(path)
            if not any(l.strip() and not l.strip().startswith("//") for l in self.read(path).split("\n")):
                continue  # a comment-only placeholder is not code
            m = re.match(r"Packages/([^/]+)/(Sources|Tests)/", rel)
            if m:
                mods[m.group(1)][0 if m.group(2) == "Sources" else 1] += 1
            elif rel.startswith("App/"):
                mods["App"][0] += 1
            elif rel.startswith("AppTests/"):
                mods["App"][1] += 1
        counted = {k: v for k, v in mods.items() if k not in ("CoreModel", "CoreLocalization", "CoreTesting")}
        total_main = sum(v[0] for v in counted.values())
        total_test = sum(v[1] for v in counted.values())
        ratio = (total_test / total_main) if total_main else 0.0
        for mod, (main, test) in sorted(counted.items()):
            base = os.path.join(self.root, "Packages", mod)
            if mod.startswith("Feature") and main and test / main < MIN_FEATURE_TEST_RATIO:
                self.add("TEST-02", "violation", base, 1, "feature test/source ratio %.2f (%d/%d) < %.1f: add screen, item and mapper tests"
                         % (test / main, test, main, MIN_FEATURE_TEST_RATIO))
            elif main >= 3 and test / main < MIN_TEST_RATIO:
                self.add("TEST-02", "warning", base, 1, "test/source ratio %.2f (%d/%d) < %.1f" % (test / main, test, main, MIN_TEST_RATIO))
        if not self.module and total_main and ratio < MIN_TEST_RATIO:
            self.add("TEST-02", "violation" if self.final else "warning", self.root, 1, "project test/source ratio %.2f < %.1f" % (ratio, MIN_TEST_RATIO))
        return {"main_files": total_main, "test_files": total_test, "ratio": round(ratio, 2)}

    def scan_view_tests(self):
        """TEST-04: every internal or public view type in a feature, CoreUI or CoreDesignSystem has a test that mentions it."""
        for source in self.files({".swift"}, os.path.join(self.root, "Packages")):
            rel = self.rel(source)
            m = re.match(r"Packages/(Feature\w+|CoreUI|CoreDesignSystem)/Sources/", rel)
            if not m or (self.module and not rel.startswith(self.module)):
                continue
            base = os.path.basename(source)
            if base.endswith(("Route.swift", "Navigation.swift", "PreviewData.swift")):
                continue
            tests = "\n".join(self.read(p) for p in self.files({".swift"}, os.path.join(self.root, "Packages", m.group(1), "Tests")))
            text = self.strip_comments(self.read(source))
            for t in re.finditer(r"^(?:public\s+|internal\s+)?struct\s+(\w+)\s*:\s*View\b", text, re.MULTILINE):
                if not re.search(r"\b%s\b" % t.group(1), tests):
                    self.add("TEST-04", "violation", source, text[:t.start()].count("\n") + 1,
                             "%s has no ViewInspector test: render each state and check texts and callbacks" % t.group(1))

    def run(self):
        self.reason_apis, self.usage_apis = {}, {}
        self.scan_swift()
        self.scan_packages()
        self.scan_files_and_secrets()
        self.scan_strings()
        self.scan_privacy()
        self.scan_view_tests()
        ratio = self.test_ratio()
        violations = [f for f in self.findings if f["severity"] == "violation"]
        return {"violations": len(violations), "warnings": len(self.findings) - len(violations),
                "test_ratio": ratio, "findings": self.findings}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("root")
    ap.add_argument("--module", help="limit the scan to one path, e.g. Packages/FeatureNotesList or App")
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--final", action="store_true", help="Stage E: enforce the project-wide test ratio")
    args = ap.parse_args()
    result = Scanner(args.root, args.module, args.final).run()
    if args.json:
        print(json.dumps(result, indent=1))
    else:
        for f in sorted(result["findings"], key=lambda f: (f["severity"] != "violation", f["file"], f["line"])):
            tag = "VIOLATION" if f["severity"] == "violation" else "WARNING"
            print("%-9s %-8s %s:%s  %s" % (tag, f["rule"], f["file"], f["line"], f["message"]))
        print("check_rules: %d violation(s), %d warning(s), test ratio %.2f (%d/%d)"
              % (result["violations"], result["warnings"], result["test_ratio"]["ratio"],
                 result["test_ratio"]["test_files"], result["test_ratio"]["main_files"]))
    sys.exit(1 if result["violations"] else 0)


if __name__ == "__main__":
    main()
